### ISSUE TITLE
Cannot run models with specific tags

### ISSUE THREAD

**Issue by thepushkarp** [PromptMixerDev/prompt-mixer-ollama-connector#17]
## Bug

Hi, thanks for adding an Ollama Connector to PromptMixer. It's super convenient to have a list of all the Ollama models through a picker.

![image](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/42088801/df76d4ac-5bee-4648-a540-3b58c8540420)

However, I have noticed that this list does not contain the specific tags of the models that I have locally installed and points only to the models having the `:latest` tag by default.

For example, I downloaded the `wizardlm2:7b` (which although is the exact same model as the `wizardlm2:latest`, ollama differentiates it because it has a different tag) but when I select `wizardlm2` from the list, it returns an error, possibly because it looks for the `:latest` model [Screenshots attached].

![image](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/42088801/66d93972-e00e-4362-8ef4-d090c31c9ab1)

<img width="491" alt="image" src="https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/42088801/ab631a52-ba04-4b94-b4f7-80f3ed83587c">

![image](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/42088801/acbd412e-a400-4448-8f91-40f1022d43c9)

---

## Possible Solution

I do not know how the [config.js](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/blob/main/config.js) file is implemented inside the PromptMixer app, but is it possible to call the Ollama's default `http://localhost:11434/api/tags` GET API and get a list of all the locally installed models and have them in the list?

This would make it possible to infer all posible tags of Ollama models via PromptMixer.

Thanks!

**Comment by tomatyss** [comment]
Thank you! Good catch. We will add a dynamic list of models based on the ones that are installed.

**Comment by tomatyss** [comment]
@thepushkarp FYI In the latest version of the connector, only the installed models are displayed by default.
