### ISSUE TITLE
Ollama Connector Not Appearing in Installed List (Prompt Mixer v0.2.4)

### ISSUE THREAD

**Issue by 100pearlcent** [PromptMixerDev/prompt-mixer-ollama-connector#79]
I'd like to start by thanking you for creating the Ollama connector.

OS: macOS Ventura 13.4
Chip: Apple M2
I'm currently using the latest version of Prompt Mixer (v0.2.4).

I successfully downloaded the Ollama Connector, as shown in the attached image.
![스크린샷 2024-07-09 오후 4 30 24](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/5b0a23fe-da5b-4f3f-8f2e-0c1de68ec7d8)

However, it's not showing up in the installed list within Prompt Mixer.

![스크린샷 2024-07-09 오후 4 31 42](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/acdadc7b-f3e7-44d3-a821-723884b146a5)

Can you provide any troubleshooting steps for this issue?

Thank you for your time and assistance!

**Comment by tomatyss** [comment]
@100pearlcent 

I'm sorry to hear you're experiencing this issue. Let's try to troubleshoot it together.

1. I apologize for the inconvenience you're facing with this issue.

2. I've attempted to reproduce the problem on my end but was unable to do so. This suggests it might be a localized issue.

3. To debug this, I suggest checking the following:
   After successfully installing the connector, please verify if the connector folder exists at this path:
   '/Users/<your username>/Library/Application Support/PromptMixer/connectors'
   You should see a folder named something like 'prompt-mixer-ollama-connector'.

4. If the folder exists but the connector still doesn't appear in the installed list, please open the console (press cmd+option+i) and send us a screenshot of any relevant error messages or logs.

5. If the folder doesn't exist, it might be a permissions issue. As an alternative solution, you can always download the source code of the connector, build it, and manually place it in the connectors folder. For more details on this process, please refer to our documentation: https://docs.promptmixer.dev/tutorial-extras/add-a-custom-connector

Please let me know the results of these steps, and we'll continue to work on resolving this issue for you.

Thank you for your patience and cooperation!

**Comment by 100pearlcent** [comment]
Dear @tomatyss, thanks for your quick reply!

**Following your instructions, I checked the path:**
'/Users/<my username>/Library/Application Support/PromptMixer/connectors'

**Unfortunately, the folder named 'prompt-mixer-ollama-connector' was missing, as shown in the attached image:**
![스크린샷 2024-07-10 오전 11 52 20](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/7c0ef420-415a-4fdc-aaaa-a5df048e61f1)

**Next, I tried opening the console `Cmd + Option + I` as you suggested, but I only saw the folder's properties, not any error messages or logs.**

**Since the console approach didn't work, I manually cloned the project from this URL:**

https://github.com/PromptMixerDev/prompt-mixer-ollama-connector.git

**I then ran the following commands:**

`npm i && npm run build`

**I verified that the 'main.ts' file was present.**

**Finally, I manually created the folder '/Users/<your username>/Library/Application Support/PromptMixer/connectors' and placed the application there.**

![스크린샷 2024-07-10 오후 12 57 54](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/5f98aaeb-5a72-4515-8a63-d0944a3b0d33)

**Unfortunately, the Ollama Connector still doesn't appear in my installed list.**
<img width="780" alt="스크린샷 2024-07-10 오후 1 02 52" src="https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/b18b7750-e487-4027-b700-f943b85957dd">

**I'd appreciate any further troubleshooting steps you can suggest to resolve this issue.**

Thank you!

**Comment by tomatyss** [comment]
Hi @100pearlcent ,

Thank you for providing such detailed information about the steps you've taken. Let's try to resolve this issue.

1. When I mentioned opening the console (Cmd+Option+I), I was referring to opening it within the Prompt Mixer App itself, not in Finder. This console would show any error messages or logs related to the app.

2. For manually adding a connector, you only need to add the main.js file from the build folder into the correct path. The full path should look like this:
/Users/<your username>/Library/Application Support/PromptMixer/connectors/prompt-mixer-ollama-connector/main.js

3. Here's a step-by-step process to try:
   a. Clone the git repo to a temporary location
   b. Run `npm i && npm run build` in that location
   c. Copy only the main.js file from the build folder
   d. Paste this main.js file into /Users/<your username>/Library/Application Support/PromptMixer/connectors/prompt-mixer-ollama-connector/
   e. Quit and reopen the Prompt Mixer app

4. I've attached a screenshot showing how the folder structure typically looks. You can see the prompt-mixer-ollama-connector folder contains only the main.js file.

<img width="1500" alt="Screenshot2024-07-10at07 14 37" src="https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/8049304/63e79b82-779e-42e1-9695-ac60b40daca8">


If you've followed these steps and the Ollama Connector still doesn't appear in your installed list, please try opening the console in the Prompt Mixer app (Cmd+Option+I) and check for any error messages. This information could be crucial for further troubleshooting.

Let me know if you need any clarification or if you're still experiencing issues after trying these steps.

**Comment by 100pearlcent** [comment]
Dear @tomatyss,

Thank you for your continued support!

Though after following your steps, the Ollama Connector still isn't showing up in the installed list.

Here's what I see when I press `Comm + Option + I` on the Prompt Mixer app:
![스크린샷 2024-07-11 오전 8 57 35](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/3e848ff8-8dc2-4e30-9a64-d562e648d094)

I've also tried the following troubleshooting steps:

1.Renaming `main.ts` to `main.js`
2.Adding the connector directly from the GitHub link:
![스크린샷 2024-07-11 오전 9 06 45](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/6587b143-dd31-40c3-b7c2-5ef7d8df2000)
![스크린샷 2024-07-11 오전 9 07 03](https://github.com/PromptMixerDev/prompt-mixer-ollama-connector/assets/58822023/eebd522d-5b25-405b-b912-7a13c2e2a9b1)

Unfortunately, none of these attempts have worked.

I truly appreciate your assistance.
Any further guidance you can provide would be greatly appreciated!

**Comment by tomatyss** [comment]
Hi @100pearlcent , sorry for the long response.

1. When I said to use main.js, I meant to copy main.js from the build folder, not rename main.ts.
2. If you want to install directly from GitHub, you need to use a direct link to the build and not to the repository, like https://api.github.com/repos/PromptMixerDev/prompt-mixer-ollama-connector/releases/latest
3. I'm not sure that it will help because this mechanism will work the same as installing the connector from the connector collections.
4. Just to clarify: are you using Prompt Mixer installed in the Applications directory?
5. I suggest trying to create a new folder in the connector directory, and copy main.js from the build directory directly to this folder.
6. If it doesn't help, would you mind scheduling a meeting? https://calendar.app.google/9xKWtAiJznc3YHBz7 (I hope this time range is appropriate for you). If it's not, please suggest your preferred times.
"""

**Comment by 100pearlcent** [comment]
Hi @tomatyss,

Apologies for the late reply.

I've confirmed that the Prompt Mixer app is located in the Applications folder (as shown in the attached image).
<img width="916" alt="스크린샷 2024-07-15 오전 9 46 14" src="https://github.com/user-attachments/assets/a1d59fef-3f0b-495f-8b70-16b46c161d22">

I would be grateful if we could schedule an online meeting to discuss this further.
I'm in the GMT+9 timezone and work from 9:00 AM to 6:00 PM weekdays.
Please let me know what time works best for you.

Thanks a bundle!

**Comment by 100pearlcent** [comment]
Dear @tomatyss,

I'd be happy to schedule an online meeting to discuss this further.

I'm located in a timezone that is UTC/GMT +9 hours.
On weekdays, I'm available after 6:00 PM. 
For weekends, I'm flexible and can meet anytime that works for you.

Please let me know what time would be most convenient for you.

Thank you!

**Comment by tomatyss** [comment]
Dear @100pearlcent ,

Thank you for reaching out and I apologize for the delay in my response. 

I have updated my calendar to include an available slot at 8:00 PM (20:00) your time. If this time works for you, please feel free to schedule the meeting using the following link: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2r7wINH-L4TUqbHbHezeqMW7qK7UbCsHw5G3DtAs09DW_oJ2jjnex3FMBaLalPlEb-OOvl9UVv.

If 8:00 PM is not convenient for you, please let me know and I will do my best to accommodate a time that better suits your schedule. 

Best regards!

**Comment by 100pearlcent** [comment]
Hello again!
I tried with another PC that is running on Windows OS and found it works totally fine.
Seems it is just my macOS device issue. I'll let you know the result  after trying with other macOS device later.
Thanks for your help!
